# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 14:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'permissions': (('view_public_document', 'Peut télécharger le document publique'), ('view_private_document', 'Peut télécharger le document privé'), ('add_class_note', 'Peut ajouter une note au document'))},
        ),
    ]
