# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0004_auto_20171002_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.ManyToManyField(related_name='_subcategory_category_+', to='back.Subcategory'),
        ),
    ]
