# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 16:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0005_auto_20171002_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='category',
        ),
        migrations.DeleteModel(
            name='Subcategory',
        ),
    ]
