# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0006_auto_20171002_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='subcategories',
            field=models.ManyToManyField(related_name='subcategory', to='back.Category'),
        ),
    ]
