# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 02:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0009_auto_20171002_1727'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateDocument',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='back.Document')),
            ],
            options={
                'permissions': (('view_public_document', 'Peut télécharger le document publique'), ('view_private_document', 'Peut télécharger le document privé'), ('add_class_note', 'Peut ajouter une note au document')),
            },
            bases=('back.document',),
        ),
        migrations.AlterModelOptions(
            name='document',
            options={},
        ),
    ]
