# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0011_publicdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatedocument',
            name='file',
            field=models.FileField(upload_to='uploads/private/'),
        ),
        migrations.AddField(
            model_name='publicdocument',
            name='file',
            field=models.FileField(upload_to='uploads/public/'),
        ),
    ]
