# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 16:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('back', '0012_auto_20171003_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_back.document_set+', to='contenttypes.ContentType'),
        ),
    ]
