# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 16:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0013_document_polymorphic_ctype'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='parent_tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='back.Tag'),
        ),
    ]
