# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 15:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0015_auto_20171003_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatedocument',
            name='qrcode',
            field=models.ImageField(upload_to='uploads/private/qrcode/'),
        ),
        migrations.AlterField(
            model_name='publicdocument',
            name='qrcode',
            field=models.ImageField(upload_to='uploads/public/qrcode/'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='parent_tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='back.Tag'),
        ),
    ]
