# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 16:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0020_auto_20171004_1616'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='parent_tag',
            new_name='parent',
        ),
    ]
