# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0021_auto_20171004_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(choices=[('<p class="fa fa-legal"> fa-legal </p>', '<p class="fa fa-legal"> fa-legal </p>'), ('<p class="fa fa-legal"> fa-legal </p>', '<p class="fa fa-legal"> fa-legal </p>')], default=None, max_length=50),
            preserve_default=False,
        ),
    ]
