# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0026_auto_20171005_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='alias_url',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
