# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0027_category_alias_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='content',
            field=models.TextField(max_length=5000),
        ),
    ]
