# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0030_note_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='type',
            field=models.CharField(choices=[('general', 'Note générale'), ('page', 'Note par page')], default='general', max_length=20),
        ),
    ]
